Employees/urls.py
from django.contrib import admin
from django.urls import path,  include
from .views import IndexView
from django.conf import settings
from django.conf.urls.static  import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',  IndexView.as_view(), name = "index"),
    # Apps
    path('departments/', include('applications.departments.urls')),
    path('employees/', include('applications.employees.urls')),
] + static(settings.MEDIA_URL, document_root =  settings.MEDIA_ROOT)

applications/departments/urls.py
from django.urls import path
from . import views

app_name = "department_app"

urlpatterns = [
    path('crear-departamento/', views.DepartmentCreate.as_view(), name = 'department_create'),
    path('todos/', views.ListAllDepartment.as_view(), name = 'department_all'),
]

applications/employees/urls.py
from django.urls import path
from . import views

app_name = "employee_app"

urlpatterns = [
    path('todos/', views.ListAllEmployees.as_view(), name = 'employees_all'),
    path('administrar/', views.EmployeesAdmin.as_view(), name = 'employees_all_admin'),
    path('por-departamento/<department_short_name>/', views.ListByDepartment.as_view(), name = 'employees_by_department'),
    path('habilidades-empleado/', views.ListSkillsOfEmployee.as_view(), name = 'employee_skills'),
    path('detalle-empleado/<pk>/', views.EmployeeDetail.as_view(), name = 'employee_detail'),
    path('registrar-empleado/', views.EmployeeCreate.as_view(), name = "employee_create"),
    path('editar-empleado/<pk>/', views.EmployeeUpdate.as_view(), name = 'employee_update'),
    path('eliminar-empleado/<pk>/', views.EmployeeDelete.as_view(), name = 'employee_delete')
]

applications/departments/models.py
from django.db import models

# Model for table 'departments'
class Department(models.Model):

    name = models.CharField("Nombre", max_length=50)
    # Single field, will not be repeated
    short_name  = models.CharField("Nombre Corto", max_length=20, unique=True)
    is_inactivo = models.BooleanField("Inactivo", default = False)

    # Adaptation to show in the administrator panel
    class Meta:
        verbose_name = 'Departamento'
        verbose_name_plural = "Departamentos"

    def __str__(self):
        return '(' + str(self.id) + ')   ' + self.name
    

applications/departments/forms.py
from django import forms

class CreateDepartmentForm(forms.Form):

    name       = forms.CharField(max_length = 50)
    short_name = forms.CharField(max_length = 20)
    
    # Under the statement that a department is created when there is at least 
    # one employee in it, fields are added to request data from the 'employee'
    first_name = forms.CharField(max_length = 50)
    last_name  = forms.CharField(max_length = 50)

applications/departments/views.py
from django.shortcuts import render
from django.views.generic.edit import FormView
from django.views.generic import ListView, DetailView
from applications.employees.models import Employee
from .forms import CreateDepartmentForm
from .models import Department

class ListAllDepartment(ListView ):
    template_name = 'departments/list_all.html'
    model         = Department
    paginate_by   = 3 # genera objeto (page_obj) para manejar la paginación en el template
    
    # This type of view (ListView) manages the entire list of records in the model, 
    # so I access it through the variable that I define in this field.
    context_object_name = 'list_departments'

    def get_queryset(self):
        # Receives the 'keyword' from the URL
        keyword = self.request.GET.get("keyword", "") # Keyword is the value 'name' of the html element containing the 'keyword'
        
        # <attribute_name>__icontains, filter the search with minimal matches
        # Ex: In an array "Paralelepipedo, Paral", where keyword = 'Paral'
        # would return the two words; but if the filtering were only "full_name" (Not full_name__icontains)
        # would only return word 2 ('Paral')
        list = Department.objects.filter( name__icontains = keyword ) 
        return list


class DepartmentCreate(FormView):
    template_name = 'departments/create.html'
    form_class    =  CreateDepartmentForm
    success_url   = '/'

    def form_valid(self, form):
        # Create the department
        department = Department(
            name = form.cleaned_data["name"],
            short_name = form.cleaned_data["short_name"]
        )
        department.save()

        # Create the employee
        # By using create d this way, you don't need to do 'save()' afterwards to save to the DB
        Employee.objects.create( 
            first_name = form.cleaned_data["first_name"],
            last_name = form.cleaned_data["last_name"],
            job = '1',
            department = department,
            full_name  = form.cleaned_data["first_name"] + " " + form.cleaned_data["last_name"]
        )
        return super(DepartmentCreate, self).form_valid(form)

templates/departments/create.html
{% extends 'base.html' %}


{% block title %}
    Todos los Departamentos
{% endblock title %}

{% block content %}

    {% include "includes/header.html" %}


    <div class = "grid-container">
        <div class = "grid-x">
            <h1 class = "cell">CREAR DEPARTAMENTO</h1>

            <form class = "cell callout grid-x grid-margin-x" method="POST">
                {% csrf_token %}

                <h3 class = "medium-12">Datos del Departamento</h3>
                    
                <div class="medium-6 cell">
                    <label>Nombre: 
                        {{ form.name }}
                    </label>
                </div>

                <div class="medium-6 cell">
                    <label>Nombre corto: 
                        {{ form.short_name }}
                    </label>
                </div>
                
                
                <h3 class = "medium-12">Datos del Empleado</h3>
                <div class="medium-6 cell">
                    <label>Nombres: 
                        {{ form.first_name }}
                    </label>
                </div>

                <div class="medium-6 cell">
                    <label>Apellidos: 
                        {{ form.last_name }}
                    </label>
                </div>

                <div class="medium-12 cell">
                    <button type = "submit"  class = "button">Guardar</button>
                </div>

            </form>
        </div>
    </div>
{%  endblock content %}

templates/departments/list_all.html
{% extends 'base.html' %}


{% block title %}
    Todos los Departamentos
{% endblock title %}

{% block content %}

    {% include "includes/header.html" %}


    <div class = "grid-container">
        <div class = "grid-x">
            <h1 class = "cell" style = "margin-top: 20px; margin-bottom: 10px;">Lista de Departamentos</h1>

            <!-- start of department finder -->
            <form method = "GET" class = "cell grid-x grid-margin-x">
                {% csrf_token %}
                <div class = "cell large-7">
                    <input type="text" id = "keyword_id" name = "keyword" placeholder="Buscar departamento">
                </div>
                <div class = "cell large-2">
                    <button type = "submit" class = "success button">Buscar</button>
                </div>
            </form>
            <!-- end of department finder -->

            <!-- start of list table -->
            <div class="cell">
                <table>
                    <thead>
                        <tr>
                            <th width="50">ID</th>
                            <th width="100">DESCRIPCIÓN</th>
                            <th width="30">ACCIONES</th>
                        </tr>
                    </thead>

                    <tbody>
                        {% for department in list_departments %}
                        <tr>
                            <td>{{ department.id }}</td>
                            <td>{{ department.name }}</td>
                            <td> <a href = "{% url 'employee_app:employees_by_department' department.short_name %}" class ="warning button">Ver Empleados</a></td>                        
                        </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
            <!-- end of list table -->

            <!-- start of pagination -->
            <div class = "cell">
                {% if is_paginated %}
                    <nav aria-label="Pagination">
                        <ul class="pagination">
                            {% if page_obj.has_previous %}
                                <li class="pagination-previous">
                                    <a href="?page={{ page_obj.previous_page_number }}">Atras</a>
                                </li>
                            {% endif %}
                            
                            {% for page in paginator.page_range %}

                            {% if page == page_obj.number %}
                                <li class="current"><span class="show-for-sr">You're on page</span>{{ page }}</li>    
                            {% else %}
                                <li><a href="?page={{ page }}">{{ page }}</a></li> 
                            {% endif %}
                                
                            {% endfor %}
                            
                            {% if page_obj.has_next %}
                                <li class="pagination-next">
                                    <a href="?page={{ page_obj.next_page_number }}">Siguiente</a>
                                </li>
                            {% endif %}
                        </ul>
                    </nav>
                {% endif %}
            </div>
            <!-- end of pagination -->
        </div>
    </div>
    
{% endblock content %}