Employees/urls.py
from django.contrib import admin
from django.urls import path,  include
from .views import IndexView
from django.conf import settings
from django.conf.urls.static  import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',  IndexView.as_view(), name = "index"),
    # Apps
    path('departments/', include('applications.departments.urls')),
    path('employees/', include('applications.employees.urls')),
] + static(settings.MEDIA_URL, document_root =  settings.MEDIA_ROOT)

applications/departments/urls.py
from django.urls import path
from . import views

app_name = "department_app"

urlpatterns = [
    path('crear-departamento/', views.DepartmentCreate.as_view(), name = 'department_create'),
    path('todos/', views.ListAllDepartment.as_view(), name = 'department_all'),
]

applications/employees/urls.py
from django.urls import path
from . import views

app_name = "employee_app"

urlpatterns = [
    path('todos/', views.ListAllEmployees.as_view(), name = 'employees_all'),
    path('administrar/', views.EmployeesAdmin.as_view(), name = 'employees_all_admin'),
    path('por-departamento/<department_short_name>/', views.ListByDepartment.as_view(), name = 'employees_by_department'),
    path('habilidades-empleado/', views.ListSkillsOfEmployee.as_view(), name = 'employee_skills'),
    path('detalle-empleado/<pk>/', views.EmployeeDetail.as_view(), name = 'employee_detail'),
    path('registrar-empleado/', views.EmployeeCreate.as_view(), name = "employee_create"),
    path('editar-empleado/<pk>/', views.EmployeeUpdate.as_view(), name = 'employee_update'),
    path('eliminar-empleado/<pk>/', views.EmployeeDelete.as_view(), name = 'employee_delete')
]

templates/includes/header.html
<div class="top-bar">

    <!-- Menú de barra de navegación  -->
    <div class="top-bar-left">
      <ul class="dropdown menu" data-dropdown-menu>
        <li><a class="menu-text" href="{% url 'index' %}">EmpleaDos</a></li>
        <li><a href="{% url 'employee_app:employees_all' %}">LISTAR</a></li>
        <li><a href="{% url 'department_app:department_all' %}">DEPARTAMENTOS</a></li>
        <li><a href="{% url 'employee_app:employees_all_admin' %}">ADMINISTRAR</a></li>
        <li><a href="{% url 'department_app:department_create' %}">NUEVO DEPARTAMENTO</a></li>
      </ul>
    </div>
    
    <div class="top-bar-right">
      <ul class="menu">
        <!-- <li><input  type="search" placeholder="Buscar empleado ..."></li> -->
        <li><a href="{% url 'employee_app:employee_create' %}" class = "button">Registrar</a></li>
      </ul>
    </div>
</div>