Employees/urls.py
from django.contrib import admin
from django.urls import path,  include
from .views import IndexView
from django.conf import settings
from django.conf.urls.static  import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',  IndexView.as_view(), name = "index"),
    # Apps
    path('departments/', include('applications.departments.urls')),
    path('employees/', include('applications.employees.urls')),
] + static(settings.MEDIA_URL, document_root =  settings.MEDIA_ROOT)

applications/employees/urls.py
from django.urls import path
from . import views

app_name = "employee_app"

urlpatterns = [
    path('todos/', views.ListAllEmployees.as_view(), name = 'employees_all'),
    path('administrar/', views.EmployeesAdmin.as_view(), name = 'employees_all_admin'),
    path('por-departamento/<department_short_name>/', views.ListByDepartment.as_view(), name = 'employees_by_department'),
    path('habilidades-empleado/', views.ListSkillsOfEmployee.as_view(), name = 'employee_skills'),
    path('detalle-empleado/<pk>/', views.EmployeeDetail.as_view(), name = 'employee_detail'),
    path('registrar-empleado/', views.EmployeeCreate.as_view(), name = "employee_create"),
    path('editar-empleado/<pk>/', views.EmployeeUpdate.as_view(), name = 'employee_update'),
    path('eliminar-empleado/<pk>/', views.EmployeeDelete.as_view(), name = 'employee_delete')
]

applications/employees/models.py
from django.db import models
# Related model import
from applications.departments.models import Department



# Model for table 'Skills'
class Skills(models.Model):
    skill =  models.CharField("Habilidad", max_length = 50)

    # Adaptation to show in the administrator panel
    class Meta:
        verbose_name = 'Skill'
        verbose_name_plural = "Skills"

    def __str__(self):
         return self.skill


# Model for table 'Employees'
class Employee(models.Model):

    # Choice
    JOB_CHOICES = (
        ('O', 'Generente'),
        ('1', "Administrador"),
        ('2', "Analista"),
        ('3', "Obrero"),
        ('4', "Contador"),
    )

    first_name = models.CharField("Nombre", max_length = 50)
    last_name  = models.CharField("Apellido", max_length = 50)
    full_name  = models.CharField("Nombre Completo", max_length = 100)
    avatar     = models.ImageField(upload_to = 'employees', blank = True, null = True) 
    job        = models.CharField("Cargo", max_length  = 1, choices = JOB_CHOICES)
    
    # Foreign keys
    department = models.ForeignKey(Department, on_delete = models.CASCADE)
    skills     =  models.ManyToManyField(Skills)
    
    # Adaptation to show in the administrator panel
    class Meta:
        verbose_name = 'Empleado'
        verbose_name_plural = "Empleados"

    def __str__(self):
         return '(' + str(self.id) + ') ' + self.first_name + " " +self.last_name

applications/employees/forms.py
from django import forms
from .models import Employee

class EmployeeForm(forms.ModelForm):

    class Meta:
        model  = Employee
        # fields = ('__all__')
        fields = ["first_name","last_name","avatar","job","department","skills",]

        # I can access and modify the html attributes from the 'widgets' context variable
        widgets = {
            # Example: 'first_name' is how I declared the field in the model
            'first_name': forms.TextInput(
                attrs = {
                    'placeholder': "Primer nombre ... ",
                    
                }
            ),
            'last_name': forms.TextInput(
                attrs = {
                    'placeholder': "Apellido ... "
                }
            ),
            
            'skills': forms.CheckboxSelectMultiple()
        }

    # One of the ways to perform form validations
    def clean_department(self):
        department = self.cleaned_data['department']
        if department.name == 'Analisis en Servicios TI':
            raise forms.ValidationError('No hay vacantes disponibles en "Analisis en Servicios TI"')

        return department

Employees/views.py
from django.views.generic import TemplateView


""" View that loads the system home page """
class IndexView(TemplateView):
    # Name of the template associated with this view
    template_name = 'index.html'
    

applications/employees/views.py
from django.shortcuts import render
from django.views.generic import ListView, DetailView, CreateView, TemplateView, UpdateView, DeleteView
from .models import Employee
from django.urls import reverse_lazy
from .forms import EmployeeForm


""" List all the employees of the company """
class ListAllEmployees(ListView):
    # Name of the template associated with this view
    template_name = 'employees/list_all.html'
    model         = Employee
    paginate_by   = 10 # genera objeto (page_obj) para manejar la paginación en el template
    # This type of view (ListView) manages the entire list of records in the model, 
    # so I access it through the variable that I define in this field.
    context_object_name = 'list_employees'

    def get_queryset(self):
        # Receives the 'keyword' from the URL
        keyword = self.request.GET.get("keyword", "") # Keyword is the value 'name' of the html element containing the 'keyword'
        
        # <attribute_name>__icontains, filter the search with minimal matches
        # Ex: In an array "Paralelepipedo, Paral", where keyword = 'Paral'
        # would return the two words; but if the filtering were only "full_name" (Not full_name__icontains)
        # would only return word 2 ('Paral')
        list = Employee.objects.filter( full_name__icontains = keyword ) 
        return list


""" List all employees belonging to a company department """
class ListByDepartment(ListView):
    # Name of the template associated with this view
    template_name = 'employees/list_by_department.html'
    
    # Filter list of employees, by 'department'
    # queryset      = Employee.objects.filter( department__name = 'Contabilidad y Finanzas interiores' ) # Two underscores (__) and then the model attribute (name)
    def get_queryset(self):
        # Receives the 'short_name' from the URL
        department = self.kwargs['department_short_name']
        list = Employee.objects.filter( department__short_name = department ) # Two underscores (__) and then the model raltionsship attribute (short_name)
        return list
    
    # This type of view (ListView) manages the entire list of records in the model, 
    # so I access it through the variable that I define in this field.
    context_object_name = 'list_employees_by_deparment'

""" List skills of an employee """
class ListSkillsOfEmployee(ListView):
    template_name       = 'employees/list_skills.html'
    context_object_name = 'list_skills'

    def get_queryset(self):
        # Receives the 'keyword' from the URL
        employee_id = self.request.GET.get("employee", "") # employee_id is the value 'name' of the html element containing the employee id
        if employee_id != '':
            employee = Employee.objects.get(id = employee_id )
            return employee.skills.all()
        return []

class EmployeeDetail(DetailView):
    template_name       = 'employees/detail_employee.html'
    model               = Employee
    context_object_name = 'object_detail'

class EmployeeCreate(CreateView):
    template_name = 'employees/create.html'
    model         = Employee
    
    # Extra field queredio in the 'CreateView', referred to the model attributes
    # fields        = ('__all__')
    # fields = ["first_name","last_name","job","department","skills", "avatar"] # The 'fields' decorator handles a default variable
    #                                                                 # called 'form' referring to the fields indicated in 
    #                                                                 # its declaration. it can be accessed in the .html 
    #                                                                 # template
    

    # If I use 'ModelForm' to be able to manipulate the fields of the form, 
    # it is allowed to replace 'fields' with 'form_call'
    form_class =  EmployeeForm
    
    
    # I must indicate which URL to go to when the request is successfully completed
    # success_url = '/employees/todos' # Redirect to the same page
    success_url   = reverse_lazy('employee_app:employees_all') 


    def form_valid(self, form):
        employee = form.save(commit = False) # Creates instance as it will go to database, but doesn't waste memory on save
        employee.full_name = employee.first_name + " " + employee.last_name
        employee.save()
        return super(EmployeeCreate, self).form_valid(form)


class EmployeeUpdate(UpdateView):
    template_name = 'employees/update.html'
    model         = Employee
    fields        = ["first_name","last_name","job","department","skills"]
    success_url   = reverse_lazy('employee_app:employees_all_admin')


    # def post(self, request, *args, **kwargs):
    #     self.object = self.get_object()
    #     print(request.POST) # I can access the values ​​received by the 'request'
    #     return super().post(request, *args, **kwargs)

    def form_valid(self, form):
        employee = form.save(commit = False) # Creates instance as it will go to database, but doesn't waste memory on save
        employee.full_name = employee.first_name + " " + employee.last_name
        employee.save()
        return super(EmployeeUpdate, self).form_valid(form)


class EmployeeDelete(DeleteView):
    model = Employee
    # When 'delete' it is sometimes necessary to confirm the deletion, for this reason a 'template_name' is silvered
    template_name = 'employees/delete.html'
    success_url = reverse_lazy('employee_app:employees_all_admin')

class EmployeesAdmin(ListView):
    template_name = 'employees/list_all_admin.html'
    model         = Employee
    paginate_by   = 5
    context_object_name = 'list_employees'

templates/employees/create.html
{% extends 'base.html' %}


{% block title %}
    Todos los empleados
{% endblock title %}

{% block content %}

    {% include "includes/header.html" %}
    <div class = "grid-container">
        <div class = "grid-x">
            <h1 class = "cell"  style = "margin-top: 20px; margin-bottom: 10px;">CREAR NUEVO EMPLEADO</h1>
        </div>

        <div class = "cell">
            <form class = "grid-x grid-margin-x" action="" method="POST" enctype="multipart/form-data">
                {% csrf_token %}

                <div class="cell large-6">
                    <label>Nombres:
                        {{ form.first_name }}
                    </label>
                </div>
                
                <div class="cell large-6">
                    <label>Apellidos:
                        {{ form.last_name }}
                    </label>
                </div>
                
                <div class="cell large-6">
                    <label>Cargo:
                        {{ form.job }}
                    </label>
                </div>

                <div class="cell large-6">
                    <label>Departamento:
                        {{ form.department }}
                    </label>
                </div>

                <div class="cell large-12">
                    <label>Habilidades:
                        {{ form.skills }}
                    </label>
                </div>

                
                <div class="cell large-6">
                    <label>Foto:
                        {{ form.avatar }}
                    </label>
                </div>

                <div class="cell">
                    <button class="submit success button">Regitrar</button>
                </div>             
            </form>
        </div>
    </div>
    
{% endblock content %}

templates/employees/delete.html
{% extends 'base.html' %}

{% block title %}
    Eliminar empleado
{% endblock title %}

{% block content %}

    {% include "includes/header.html" %}
    <div class = "grid-container">
        <div class = "grid-x">
            <h1 class = "cell"  style = "margin-top: 20px; margin-bottom: 10px;">Eliminar a {{ object.full_name }}</h1>
            
            <form class = "cell" action="" method="post">
                {% csrf_token %}
                
                <div class="callout secondary">
                    <h5>¿ Desea eliminar este empleado ?</h5>
                    <button type="sublit" class="alert button">Confirmar</button>
                </div>
            </form>
        </div>
    </div>
    
{% endblock content %}

templates/employees/detail_employee.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
    {{ object_detail.full_name }}
{% endblock title %}

{% block content %}

    {% include "includes/header.html" %}

    <div class = "grid-container">
        <div class = "grid-x grid-margin-x align-center">
            <div class="cell large-6 card" style="width: 500px; margin-top: 10px;">
                <div class="card-divider">
                  {{ object_detail.get_job_display }}  <!-- cuando la propiedad en un choices en el modelo -->
                </div>

                {% if object_detail.avatar %}
                    <img src="{{ object_detail.avatar.url }}">
                {% else %}
                    <img src="{% static 'images/avatar_default.png' %}">
                {% endif %}
                
                <div class="card-section">
                    <h4>{{ object_detail.full_name }}</h4>
                    <p>{{ object_detail.first_name }}</p>
                    <p>{{ object_detail.department.short_name }}</p>
                    <p><span class = "label">Habilidades:</span></p>
                    <ul class = "vertical menu">
                        {% for skill in object_detail.skills.all %}
                            <li>{{ skill.skill }}</li>
                        {% endfor %}
                    </ul>
                   
                </div>

            </div>
        </div>
    </div>

{% endblock content %}

templates/employees/list_all.html
{% extends 'base.html' %}


{% block title %}
    Todos los empleados
{% endblock title %}

{% block content %}

    {% include "includes/header.html" %}


    <div class = "grid-container">
        <div class = "grid-x">
            <h1 class = "cell" style = "margin-top: 20px; margin-bottom: 10px;">Lista de Empleados</h1>

            <!-- start of employee finder -->
            <form method = "GET" class = "cell grid-x grid-margin-x">
                {% csrf_token %}
                <div class = "cell large-7">
                    <input type="text" id = "keyword_id" name = "keyword" placeholder="Buscar empleado">
                </div>
                <div class = "cell large-2">
                    <button type = "submit" class = "success button">Buscar</button>
                </div>
            </form>
            <!-- end of employee finder -->

            <!-- start of list table -->
            <div class="cell">
                <table>
                    <thead>
                        <tr>
                            <th width="50">ID</th>
                            <th width="100">NOMBRE</th>
                            <th width="100">APELLIDOS</th>
                            <th width="200">DEPARTAMENTO</th>
                            <th width="200">ACCIONES</th>
                        </tr>
                    </thead>

                    <tbody>
                        {% for employee in list_employees %}
                        <tr>
                            <td>{{ employee.id }}</td>
                            <td>{{ employee.first_name }}</td>
                            <td>{{ employee.last_name }}</td>
                            <td>{{ employee.department.name }}</td>
                            <td><a style="margin-right: 5px;" href = "{% url 'employee_app:employee_detail' employee.id %}" class ="warning button">Ver </a></td>                        
                        </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
            <!-- end of list table -->

            <!-- start of pagination -->
            <div class = "cell">
                {% if is_paginated %}
                    <nav aria-label="Pagination">
                        <ul class="pagination">
                            {% if page_obj.has_previous %}
                                <li class="pagination-previous">
                                    <a href="?page={{ page_obj.previous_page_number }}">Atras</a>
                                </li>
                            {% endif %}
                            
                            {% for page in paginator.page_range %}

                            {% if page == page_obj.number %}
                                <li class="current"><span class="show-for-sr">You're on page</span>{{ page }}</li>    
                            {% else %}
                                <li><a href="?page={{ page }}">{{ page }}</a></li> 
                            {% endif %}
                                
                            {% endfor %}
                            
                            {% if page_obj.has_next %}
                                <li class="pagination-next">
                                    <a href="?page={{ page_obj.next_page_number }}">Siguiente</a>
                                </li>
                            {% endif %}
                        </ul>
                    </nav>
                {% endif %}
            </div>
            <!-- end of pagination -->
        </div>
    </div>
    
{% endblock content %}

templates/employees/list_all_admin.html
{% extends 'base.html' %}


{% block title %}
    Todos los empleados
{% endblock title %}

{% block content %}

    {% include "includes/header.html" %}


    <div class = "grid-container">
        <div class = "grid-x">
            <h1 class = "cell" style = "margin-top: 20px; margin-bottom: 10px;">Administrar Empleados</h1>

            <!-- start of list table -->
            <div class="cell">
                <table>
                    <thead>
                        <tr>
                            <th width="50">ID</th>
                            <th width="100">NOMBRE</th>
                            <th width="100">APELLIDOS</th>
                            <th width="200">DEPARTAMENTO</th>
                            <th width="200">ACCIONES</th>
                        </tr>
                    </thead>

                    <tbody>
                        {% for employee in list_employees %}
                        <tr>
                            <td>{{ employee.id }}</td>
                            <td>{{ employee.first_name }}</td>
                            <td>{{ employee.last_name }}</td>
                            <td>{{ employee.department.name }}</td>
                            <td>
                                <div class="button-group" >
                                    <a style="margin-right: 5px;" href = "{% url 'employee_app:employee_update' employee.id %}" class ="success button">Editar</a>
                                    <a style="margin-right: 5px;" href = "{% url 'employee_app:employee_delete' employee.id %}" class ="alert button">Eliminar</a>
                                </div>
                            </td>                        
                        </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
            <!-- end of list table -->

            <!-- start of pagination -->
            <div class = "cell">
                {% if is_paginated %}
                    <nav aria-label="Pagination">
                        <ul class="pagination">
                            {% if page_obj.has_previous %}
                                <li class="pagination-previous">
                                    <a href="?page={{ page_obj.previous_page_number }}">Atras</a>
                                </li>
                            {% endif %}
                            
                            {% for page in paginator.page_range %}

                            {% if page == page_obj.number %}
                                <li class="current"><span class="show-for-sr">You're on page</span>{{ page }}</li>    
                            {% else %}
                                <li><a href="?page={{ page }}">{{ page }}</a></li> 
                            {% endif %}
                                
                            {% endfor %}
                            
                            {% if page_obj.has_next %}
                                <li class="pagination-next">
                                    <a href="?page={{ page_obj.next_page_number }}">Siguiente</a>
                                </li>
                            {% endif %}
                        </ul>
                    </nav>
                {% endif %}
            </div>
            <!-- end of pagination -->
        </div>
    </div>
    
{% endblock content %}

templates/employees/list_by_department.html
{% extends 'base.html' %}

{% block title %}
    Empleados por departamento
{% endblock title %}

{% block content %}

    {% include "includes/header.html" %}

    <div class = "grid-container">
        <div class = "grid-x">
            <h1 class = "cell">EMPLEADOS POR DEPARMANETO</h1>

            <!-- start of list table -->
            <div class="cell">
                <table>
                    <thead>
                        <tr>
                            <th width="50">ID</th>
                            <th width="100">NOMBRE</th>
                            <th width="100">APELLIDOS</th>
                            <th width="200">DEPARTAMENTO</th>
                            <th width="30">ACCIONES</th>
                        </tr>
                    </thead>

                    <tbody>
                        {% for employee in list_employees_by_deparment %}
                        <tr>
                            <td>{{ employee.id }}</td>
                            <td>{{ employee.first_name }}</td>
                            <td>{{ employee.last_name }}</td>
                            <td>{{ employee.department.name }}</td>
                            <td> <a href = "{% url 'employee_app:employee_detail' employee.id %}" class ="warning button">Ver</a></td>                        
                        </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
            <!-- end of list table -->

        </div>
    </div>
    
{% endblock content %}

templates/employees/list_skills.html
<h1>LISTA DE HABILIDADES DE EMPLEADO</h1>

<form action="" method="GET">
    {% csrf_token %}
    <input type = "text" id = "employee_id" name = "employee" placeholder = "Ingrese ID aqui ...">
    <button  type = "submit">Buscar</button>
</form>

<ul>
    {% for skill in  list_skills %}
        <li>{{ skill }}</li>
    {% endfor %}
</ul>

templates/employees/update.html
{% extends 'base.html' %}


{% block title %}
    Todos los empleados
{% endblock title %}

{% block content %}

    {% include "includes/header.html" %}
    <div class = "grid-container">
        <div class = "grid-x">
            <h1 class = "cell"  style = "margin-top: 20px; margin-bottom: 10px;">Actualizar Empleado</h1>
        </div>
        
        <div class = "cell">
            <form class = "grid-x grid-margin-x" action="" method="POST">
                {% csrf_token %}

                <div class="cell large-6">
                    <label>Nombres:
                        {{ form.first_name }}
                    </label>
                </div>
                
                <div class="cell large-6">
                    <label>Apellidos:
                        {{ form.last_name }}
                    </label>
                </div>
                
                <div class="cell large-6">
                    <label>Cargo:
                        {{ form.job }}
                    </label>
                </div>

                <div class="cell large-6">
                    <label>Departamento:
                        {{ form.department }}
                    </label>
                </div>

                <div class="cell large-6">
                    <label>Habilidades:
                        {{ form.skills }}
                    </label>
                </div>

                <div class="cell">
                    <button class="submit success button">Actualizar</button>
                </div>             
            </form>
        </div>
    </div>

{% endblock content %}